// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ConsentWrite consent write
//
// swagger:model ConsentWrite
type ConsentWrite struct {

	// org Uid
	// Required: true
	// Format: uuid
	OrgUID *strfmt.UUID `json:"orgUid"`

	// person Uid
	// Required: true
	// Format: uuid
	PersonUID *strfmt.UUID `json:"personUid"`

	// purpose
	// Required: true
	Purpose *ConsentPurpose `json:"purpose"`

	// valid from
	// Required: true
	// Format: date-time
	ValidFrom *strfmt.DateTime `json:"validFrom"`

	// valid to
	// Format: date-time
	ValidTo *strfmt.DateTime `json:"validTo,omitempty"`
}

// Validate validates this consent write
func (m *ConsentWrite) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrgUID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePersonUID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePurpose(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValidFrom(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValidTo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConsentWrite) validateOrgUID(formats strfmt.Registry) error {

	if err := validate.Required("orgUid", "body", m.OrgUID); err != nil {
		return err
	}

	if err := validate.FormatOf("orgUid", "body", "uuid", m.OrgUID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ConsentWrite) validatePersonUID(formats strfmt.Registry) error {

	if err := validate.Required("personUid", "body", m.PersonUID); err != nil {
		return err
	}

	if err := validate.FormatOf("personUid", "body", "uuid", m.PersonUID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ConsentWrite) validatePurpose(formats strfmt.Registry) error {

	if err := validate.Required("purpose", "body", m.Purpose); err != nil {
		return err
	}

	if err := validate.Required("purpose", "body", m.Purpose); err != nil {
		return err
	}

	if m.Purpose != nil {
		if err := m.Purpose.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("purpose")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("purpose")
			}
			return err
		}
	}

	return nil
}

func (m *ConsentWrite) validateValidFrom(formats strfmt.Registry) error {

	if err := validate.Required("validFrom", "body", m.ValidFrom); err != nil {
		return err
	}

	if err := validate.FormatOf("validFrom", "body", "date-time", m.ValidFrom.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ConsentWrite) validateValidTo(formats strfmt.Registry) error {
	if swag.IsZero(m.ValidTo) { // not required
		return nil
	}

	if err := validate.FormatOf("validTo", "body", "date-time", m.ValidTo.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this consent write based on the context it is used
func (m *ConsentWrite) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePurpose(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConsentWrite) contextValidatePurpose(ctx context.Context, formats strfmt.Registry) error {

	if m.Purpose != nil {

		if err := m.Purpose.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("purpose")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("purpose")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConsentWrite) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConsentWrite) UnmarshalBinary(b []byte) error {
	var res ConsentWrite
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
