// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NationalID national Id
//
// swagger:model NationalId
type NationalID struct {

	// country iso2 code
	// Required: true
	CountryIso2Code *string `json:"countryIso2Code"`

	// id
	// Required: true
	ID *string `json:"id"`
}

// Validate validates this national Id
func (m *NationalID) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCountryIso2Code(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NationalID) validateCountryIso2Code(formats strfmt.Registry) error {

	if err := validate.Required("countryIso2Code", "body", m.CountryIso2Code); err != nil {
		return err
	}

	return nil
}

func (m *NationalID) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this national Id based on context it is used
func (m *NationalID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NationalID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NationalID) UnmarshalBinary(b []byte) error {
	var res NationalID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
