// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrgWritePatch org write patch
//
// swagger:model OrgWritePatch
type OrgWritePatch struct {

	// active status
	ActiveStatus struct {
		OrgActiveStatus
	} `json:"activeStatus,omitempty"`

	// billing address
	BillingAddress *Address `json:"billingAddress,omitempty"`

	// district name
	// Max Length: 255
	DistrictName string `json:"districtName,omitempty"`

	// name
	// Max Length: 255
	Name string `json:"name,omitempty"`

	// postal address
	PostalAddress *Address `json:"postalAddress,omitempty"`

	// type
	Type struct {
		OrgType
	} `json:"type,omitempty"`

	// visiting address
	VisitingAddress *Address `json:"visitingAddress,omitempty"`
}

// Validate validates this org write patch
func (m *OrgWritePatch) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateActiveStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBillingAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDistrictName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePostalAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVisitingAddress(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrgWritePatch) validateActiveStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.ActiveStatus) { // not required
		return nil
	}

	return nil
}

func (m *OrgWritePatch) validateBillingAddress(formats strfmt.Registry) error {
	if swag.IsZero(m.BillingAddress) { // not required
		return nil
	}

	if m.BillingAddress != nil {
		if err := m.BillingAddress.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("billingAddress")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("billingAddress")
			}
			return err
		}
	}

	return nil
}

func (m *OrgWritePatch) validateDistrictName(formats strfmt.Registry) error {
	if swag.IsZero(m.DistrictName) { // not required
		return nil
	}

	if err := validate.MaxLength("districtName", "body", m.DistrictName, 255); err != nil {
		return err
	}

	return nil
}

func (m *OrgWritePatch) validateName(formats strfmt.Registry) error {
	if swag.IsZero(m.Name) { // not required
		return nil
	}

	if err := validate.MaxLength("name", "body", m.Name, 255); err != nil {
		return err
	}

	return nil
}

func (m *OrgWritePatch) validatePostalAddress(formats strfmt.Registry) error {
	if swag.IsZero(m.PostalAddress) { // not required
		return nil
	}

	if m.PostalAddress != nil {
		if err := m.PostalAddress.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postalAddress")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("postalAddress")
			}
			return err
		}
	}

	return nil
}

func (m *OrgWritePatch) validateType(formats strfmt.Registry) error {
	if swag.IsZero(m.Type) { // not required
		return nil
	}

	return nil
}

func (m *OrgWritePatch) validateVisitingAddress(formats strfmt.Registry) error {
	if swag.IsZero(m.VisitingAddress) { // not required
		return nil
	}

	if m.VisitingAddress != nil {
		if err := m.VisitingAddress.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("visitingAddress")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("visitingAddress")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this org write patch based on the context it is used
func (m *OrgWritePatch) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateActiveStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateBillingAddress(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePostalAddress(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVisitingAddress(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrgWritePatch) contextValidateActiveStatus(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

func (m *OrgWritePatch) contextValidateBillingAddress(ctx context.Context, formats strfmt.Registry) error {

	if m.BillingAddress != nil {

		if swag.IsZero(m.BillingAddress) { // not required
			return nil
		}

		if err := m.BillingAddress.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("billingAddress")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("billingAddress")
			}
			return err
		}
	}

	return nil
}

func (m *OrgWritePatch) contextValidatePostalAddress(ctx context.Context, formats strfmt.Registry) error {

	if m.PostalAddress != nil {

		if swag.IsZero(m.PostalAddress) { // not required
			return nil
		}

		if err := m.PostalAddress.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postalAddress")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("postalAddress")
			}
			return err
		}
	}

	return nil
}

func (m *OrgWritePatch) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

func (m *OrgWritePatch) contextValidateVisitingAddress(ctx context.Context, formats strfmt.Registry) error {

	if m.VisitingAddress != nil {

		if swag.IsZero(m.VisitingAddress) { // not required
			return nil
		}

		if err := m.VisitingAddress.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("visitingAddress")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("visitingAddress")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrgWritePatch) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrgWritePatch) UnmarshalBinary(b []byte) error {
	var res OrgWritePatch
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
