// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RelationWritePatch relation write patch
//
// swagger:model RelationWritePatch
type RelationWritePatch struct {

	// Permission of target on origin
	GrantToOrigin GrantType `json:"grantToOrigin,omitempty"`

	// Permission of origin on target
	GrantToTarget GrantType `json:"grantToTarget,omitempty"`

	// origin Uid
	// Format: uuid
	OriginUID strfmt.UUID `json:"originUid,omitempty"`

	// target Uid
	// Format: uuid
	TargetUID strfmt.UUID `json:"targetUid,omitempty"`

	// Type of the relation, defined as {origin} is {type} (of) {target}
	Type struct {
		RelationType
	} `json:"type,omitempty"`

	// valid from
	// Format: date-time
	ValidFrom strfmt.DateTime `json:"validFrom,omitempty"`

	// valid to
	// Format: date-time
	ValidTo *strfmt.DateTime `json:"validTo,omitempty"`
}

// Validate validates this relation write patch
func (m *RelationWritePatch) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGrantToOrigin(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGrantToTarget(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOriginUID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTargetUID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValidFrom(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValidTo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RelationWritePatch) validateGrantToOrigin(formats strfmt.Registry) error {
	if swag.IsZero(m.GrantToOrigin) { // not required
		return nil
	}

	return nil
}

func (m *RelationWritePatch) validateGrantToTarget(formats strfmt.Registry) error {
	if swag.IsZero(m.GrantToTarget) { // not required
		return nil
	}

	return nil
}

func (m *RelationWritePatch) validateOriginUID(formats strfmt.Registry) error {
	if swag.IsZero(m.OriginUID) { // not required
		return nil
	}

	if err := validate.FormatOf("originUid", "body", "uuid", m.OriginUID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *RelationWritePatch) validateTargetUID(formats strfmt.Registry) error {
	if swag.IsZero(m.TargetUID) { // not required
		return nil
	}

	if err := validate.FormatOf("targetUid", "body", "uuid", m.TargetUID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *RelationWritePatch) validateType(formats strfmt.Registry) error {
	if swag.IsZero(m.Type) { // not required
		return nil
	}

	return nil
}

func (m *RelationWritePatch) validateValidFrom(formats strfmt.Registry) error {
	if swag.IsZero(m.ValidFrom) { // not required
		return nil
	}

	if err := validate.FormatOf("validFrom", "body", "date-time", m.ValidFrom.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *RelationWritePatch) validateValidTo(formats strfmt.Registry) error {
	if swag.IsZero(m.ValidTo) { // not required
		return nil
	}

	if err := validate.FormatOf("validTo", "body", "date-time", m.ValidTo.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this relation write patch based on the context it is used
func (m *RelationWritePatch) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateGrantToOrigin(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateGrantToTarget(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RelationWritePatch) contextValidateGrantToOrigin(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

func (m *RelationWritePatch) contextValidateGrantToTarget(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

func (m *RelationWritePatch) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *RelationWritePatch) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RelationWritePatch) UnmarshalBinary(b []byte) error {
	var res RelationWritePatch
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
